appName: backend
namespace: prod

image:
  repository: 080598576517.dkr.ecr.ap-northeast-2.amazonaws.com/prod/be
  tag: c175f75

replicas: 2

resources:
  requests:
    cpu: "500m"
    memory: "624Mi"
  limits:
    cpu: "2000m"
    memory: "1.5Gi"

config:
  # Profile
  ACTIVE_PROFILE: "prod"

  # AWS S3
  AWS_S3_BUCKET_NAME: "dev-damo-s3"
  AWS_S3_REGION: "ap-northeast-2"
  AWS_S3_DIRECTORY_PREFIX: "s3/images"

  # Kakao OAuth
  KAKAO_REDIRECT_URI: "https://damo.today/kakao/callback"
  KAKAO_RESPONSE_TYPE: "code"

  # QR
  QR_IMAGE_FORMAT: "PNG"
  QR_REDIRECT_URL: "https://damo.today/groups/preview"

  # Redis Sentinel
  SPRING_DATA_REDIS_SENTINEL_MASTER: "redis-master"
  SPRING_DATA_REDIS_SENTINEL_NODES: "redis-sentinel.prod.svc.cluster.local:26379"

  # AI
  AI_BASE_URL: "http://ai:8000"

  # APM
  ELASTIC_APM_SERVER_URL: "http://43.201.216.204:8200"
  ELASTIC_APM_SERVICE_NAME: "damo-dev-be"
  ELASTIC_APM_ENVIRONMENT: "dev"


service:
  port: 8080

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  scaleUp:
    pods: 1
    periodSeconds: 30
  scaleDown:
    stabilizationWindowSeconds: 300
    pods: 1
