name: AI Pipeline CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

env:
  HOST: ${{ secrets.AI_PROD_SERVER_HOST }}
  USER: ${{ secrets.AI_PROD_SERVER_USER }}
  PORT: ${{ secrets.AI_PROD_SERVER_PORT }}
  KEY: ${{ secrets.AI_PROD_SERVER_KEY }}

  AWS_REGION: ap-northeast-2
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  ECR_REPO_DEV: dev/ai
  ECR_REPO_PROD: prod/ai
  IMAGE_TAG: ${{ github.sha }}

  GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }} 
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  DB_NAME: ${{ secrets.DB_NAME }}

  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  LANGFUSE_SECRET_KEY: ${{ secrets.LANGFUSE_SECRET_KEY }}
  LANGFUSE_PUBLIC_KEY: ${{ secrets.LANGFUSE_PUBLIC_KEY }}
  LANGFUSE_BASE_URL: ${{ secrets.LANGFUSE_BASE_URL }}

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12.3'

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        poetry install

    # - name: Run Integration Tests
    #   run: |
    #     # run.test.sh를 활용하거나 직접 pytest 실행
    #     chmod +x run.test.sh 
    #     ./run.test.sh

  build_push:
    name: Build & Push (ECR)
    runs-on: ubuntu-24.04-arm
    needs: [ci]
    if: github.event_name == 'push' && needs.ci.result == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Resolve environment
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          IMAGE_TAG=${SHORT_SHA}
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            ECR_REPO="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO_PROD }}"
          else
            ECR_REPO="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO_DEV }}"
          fi
          echo "ECR_REPO=${ECR_REPO}" >> "$GITHUB_ENV"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> "$GITHUB_ENV"
          echo "IMAGE=${ECR_REPO}:${IMAGE_TAG}" >> "$GITHUB_ENV"
          echo "LATEST_IMAGE=${ECR_REPO}:latest" >> "$GITHUB_ENV"
          echo "DEBUG: ECR_REGISTRY=${{ env.ECR_REGISTRY }}"
          echo "DEBUG: ECR_REPO_DEV=${{ env.ECR_REPO_DEV }}"
          echo "DEBUG: Final ECR_REPO=${ECR_REPO}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE }}
            ${{ env.LATEST_IMAGE }}
          provenance: false
          sbom: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: CD (Docker deploy)
    needs: build_push
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && needs.ci.result == 'success'

    steps:
      - name: Setup WireGuard
        run: |
          sudo apt-get update && sudo apt-get install -y wireguard
          echo "${{ secrets.WG_CONF }}" | sed '/^DNS/d' | sudo tee /etc/wireguard/wg0.conf
          sudo chmod 600 /etc/wireguard/wg0.conf
          sudo wg-quick up wg0
          sudo wg show
          ping -c 3 ${{ env.HOST }} || true

      - name: Deploy via SSH (pull ECR image and run docker-compose)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USER }}
          port: ${{ env.PORT }}
          key: ${{ env.KEY }}
          timeout: 300s
          command_timeout: 60s
          envs: ECR_REGISTRY,ECR_REPO_DEV,GITHUB_SHA
          script: |
            set -euo pipefail
            cd /home/ubuntu
            
            # Debug environment variables
            echo "DEBUG: ECR_REGISTRY=${{ env.ECR_REGISTRY }}"
            echo "DEBUG: ECR_REPO_DEV=${{ env.ECR_REPO_DEV }}"
            echo "DEBUG: GITHUB_SHA=${{ github.sha }}"
            
            # Set environment variables for docker-compose
            export ECR_REPO="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPO_DEV }}"
            export IMAGE_TAG="${GITHUB_SHA:0:7}"
            echo "DEBUG: ECR_REPO=${ECR_REPO}"
            echo "DEBUG: IMAGE_TAG=${IMAGE_TAG}"
            
            # Show docker-compose file content
            echo "DEBUG: docker-compose.yml content:"
            cat docker-compose.yml || echo "No docker-compose.yml found"
            
            # Use sudo with environment variables preserved
            sudo -E ECR_REPO="${ECR_REPO}" IMAGE_TAG="${IMAGE_TAG}" docker compose pull
            sudo -E ECR_REPO="${ECR_REPO}" IMAGE_TAG="${IMAGE_TAG}" docker compose up -d
        
      - name: Teardown WireGuard
        if: always()
        run: sudo wg-quick down wg0 || true


  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [ci, deploy]
    if: always() && github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'dev')

    steps:
      - name: Send notification
        run: |
          CI_RESULT="${{ needs.ci.result }}"
          DEPLOY_RESULT="${{ needs.deploy.result }}"
          REF="${{ github.repository }}@${{ github.ref_name }}"
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          curl -H "Content-Type: application/json" \
                -X POST \
              -d "{\"username\":\"AI CI/CD\",\"content\":\"🖥️ AI CI/CD 결과\\n- CI: **${CI_RESULT}**\\n- Deploy: **${DEPLOY_RESULT}**\\n🔗 [${REF}](${RUN_URL})\"}" \
              ${{ secrets.DISCORD_WEBHOOK_URL }}
