apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: damo-ingress
  namespace: prod
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: damo.today  # 실제 도메인으로 교체 필요
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080
          - path: /ai
            pathType: Prefix
            backend:
              service:
                name: ai
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
