name: Backend CI/CD (Docker)

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

env:
  JAVA_VERSION: "21"
  AWS_REGION: ap-northeast-2

jobs:
  ci:
    name: CI (test/build)
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6380:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Wait for Redis
        run: |
          for i in {1..30}; do
            if (echo > /dev/tcp/127.0.0.1/6380) >/dev/null 2>&1; then
              echo "Redis is up"
              exit 0
            fi
            sleep 1
          done
          echo "Redis did not become ready in time"
          exit 1

      - name: Run Unit Tests
        run: ./gradlew test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: Run Integration Tests (if exists)
        run: |
          if ./gradlew -q tasks --all | grep -q "^integrationTest"; then
            ./gradlew integrationTest
          else
            echo "integrationTest task not found. Skipping."
          fi

      - name: Build bootJar
        run: ./gradlew bootJar

  build_push:
    name: Build & Push (ECR)
    runs-on: ubuntu-24.04-arm
    needs: [ci]
    if: github.event_name == 'push' && needs.ci.result == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Resolve environment
        env:
          ECR_REPO_DEV: 080598576517.dkr.ecr.ap-northeast-2.amazonaws.com/dev/be
          ECR_REPO_PROD: 080598576517.dkr.ecr.ap-northeast-2.amazonaws.com/prod/be
        run: |
          SHORT_SHA=${GITHUB_SHA::7}
          IMAGE_TAG=${SHORT_SHA}
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            ECR_REPO="${ECR_REPO_PROD}"
          else
            ECR_REPO="${ECR_REPO_DEV}"
          fi
          echo "ECR_REPO=${ECR_REPO}" >> "$GITHUB_ENV"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> "$GITHUB_ENV"
          echo "IMAGE=${ECR_REPO}:${IMAGE_TAG}" >> "$GITHUB_ENV"
          echo "LATEST_IMAGE=${ECR_REPO}:latest" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE }}
            ${{ env.LATEST_IMAGE }}
          provenance: false
          sbom: false
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: CD (Docker deploy)
    runs-on: ubuntu-latest
    needs: [build_push]
    if: github.event_name == 'push' && needs.build_push.result == 'success'

    steps:
      - name: Setup WireGuard
        run: |
          sudo apt-get update && sudo apt-get install -y wireguard
          echo "${{ secrets.WG_CONF }}" | sed '/^DNS/d' | sudo tee /etc/wireguard/wg0.conf
          sudo chmod 600 /etc/wireguard/wg0.conf
          sudo wg-quick up wg0

      - name: Deploy via SSH (pull/run)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BACK_DEV_SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -e
            cd /home/ubuntu
            sudo docker compose pull
            sudo docker compose up -d

      - name: Teardown WireGuard
        if: always()
        run: sudo wg-quick down wg0 || true

  k6:
    name: K6 (post-deploy)
    runs-on: ubuntu-latest
    needs: [deploy]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && needs.deploy.result == 'success'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run k6 (docker)
        env:
          AUTH_TOKEN: ${{ secrets.K6_AUTH_TOKEN }}
          BASE_URL: https://damo.today
          VUS: "5"
          DURATION: "30s"
        run: |
          docker run --rm \
            -e BASE_URL \
            -e VUS \
            -e DURATION \
            -e AUTH_TOKEN \
            -v "${{ github.workspace }}/k6:/k6" \
            grafana/k6 run /k6/be-k6.js

  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [ci, build_push, deploy, k6]
    if: github.event_name == 'push' && always()

    steps:
      - name: Send notification
        run: |
          CI_RESULT="${{ needs.ci.result }}"
          BUILD_RESULT="${{ needs.build_push.result }}"
          DEPLOY_RESULT="${{ needs.deploy.result }}"
          K6_RESULT="${{ needs.k6.result }}"
          REF="${{ github.repository }}@${{ github.ref_name }}"
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"username\":\"Backend CI/CD\",\"content\":\"🚀 Backend CI/CD (Docker) 결과\\n- CI: **${CI_RESULT}**\\n- Build: **${BUILD_RESULT}**\\n- Deploy: **${DEPLOY_RESULT}**\\n- K6: **${K6_RESULT}**\\n🔗 [${REF}](${RUN_URL})\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
