name: Backend CI/CD

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

env:
  HOST: ${{ secrets.BACK_PROD_SERVER_HOST }}
  REMOTE_DIR: /home/ubuntu/opt/be-prod/
  INCOMING_DIR: /home/ubuntu/opt/be-prod/incoming

  APP_NAME: spring-app
  JAR_NAME: app.jar

jobs:
  ci:
    name: CI (test/build + upload)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run Integration Tests (if exists)
        run: |
          if ./gradlew -q tasks --all | grep -q "^integrationTest"; then
            ./gradlew integrationTest
          else
            echo "integrationTest task not found. Skipping."
          fi

      - name: Build bootJar
        run: ./gradlew bootJar

      - name: Normalize bootJar to build/libs/app.jar
        run: |
          set -e
          JAR_PATH="$(ls -1 build/libs/*.jar | grep -v -- '-plain\.jar$' | head -n 1)"
          if [ -z "$JAR_PATH" ]; then
            echo "No bootJar found"
            exit 1
          fi
          echo "Selected JAR: $JAR_PATH"
          cp "$JAR_PATH" "build/libs/${{ env.JAR_NAME }}"

      # Upload
      - name: Prepare dist/app.jar
        if: github.event_name == 'push'
        #        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        run: |
          mkdir -p dist
          cp "build/libs/${{ env.JAR_NAME }}" dist/${{ env.JAR_NAME }}

      - name: Upload app.jar to Server (SCP) [main only]
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: dist/${{ env.JAR_NAME }}
          target: ${{ env.INCOMING_DIR }}/
          strip_components: 1
          overwrite: true

  deploy:
    name: CD (prod deploy)
    runs-on: ubuntu-latest
    needs: [ci]
    if: github.event_name == 'push' && needs.ci.result == 'success'
    #    if: github.event_name == 'push' && github.ref == 'refs/heads/develop' && needs.ci.result == 'success'
    steps:
      - name: Deploy via SSH (run deploy.sh) [main only]
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            set -e
            cd ${{ env.REMOTE_DIR }}

            echo "Incoming JAR path: ${{ env.INCOMING_DIR }}/${{ env.JAR_NAME }}"
            chmod +x deploy.sh
            ./deploy.sh "${{ env.INCOMING_DIR }}/${{ env.JAR_NAME }}"

  notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: [ci, deploy]
    if: always()

    steps:
      - name: Send notification
        run: |
          CI_RESULT="${{ needs.ci.result }}"
          DEPLOY_RESULT="${{ needs.deploy.result }}"
          REF="${{ github.repository }}@${{ github.ref_name }}"
          RUN_URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

          curl -H "Content-Type: application/json" \
               -X POST \
               -d "{\"username\":\"Backend CI/CD\",\"content\":\"🚀 Backend CI/CD 결과\\n- CI: **${CI_RESULT}**\\n- Deploy: **${DEPLOY_RESULT}**\\n🔗 [${REF}](${RUN_URL})\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}